language: node_js

sudo: false

node_js:
  - "7"

cache:
  apt: true
  directories:
    - node_modules

env:
 global:
   - GH_REF: git@github.com:aui/art-template.git

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts: github.com

script:
  - npm run build

branches:
  only:
  - master

after_script:
  - cd ./public
  - git init
  - git config user.name "aui"
  - git config user.email "sugarpie.tang@gmail.com"
  - git add .
  - git commit -m "[CI] update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
